### ISSUE TITLE
关于第一次会议

### ISSUE THREAD

**Issue by lcdtyph** [lcdtyph/Sweet-Home#1]
大家晚上好呀
我们打算在十一之前碰一次面，主要是详细说一下这个项目的情况以及熟悉彼此。不知道大家周日下午（或晚上）或者周二下午（或晚上）有没有时间呢？

**Comment by 79cac** [comment]
除了周日晚上其他都可以

**Comment by wuyutong96** [comment]
周一晚上九点以后不行 其它时间都可以

**Comment by lcdtyph** [comment]
周二晚上怎么样，PO周二晚上有时间
或者大家不介意的话周三中午？

**Comment by Serenayin** [comment]
有两个时间 周二晚上和周三中午 找个食堂大家聊聊就好啦
