### ISSUE TITLE
第一轮scrum

### ISSUE THREAD

**Issue by lcdtyph** [lcdtyph/Sweet-Home#2]
软工第一次会议记录
10月9日下午3:20，猫狗校园小组在上院301进行了会议。
会议主要内容如下
1.  组员自我介绍
2.  po进一步叙述需求并讨论
3.  确立编程语言

根据讨论结果，第一轮scrum开发的目标是完成校园流浪猫狗的信息展示即名片可检索的功能。主要有如下几个过程：
1.  自学php语言，限期一周。
2.  细化每个人的任务
3.  代码编写
4.  测试完善

**Comment by Serenayin** [comment]
有一个工作是大家随时都可以做的，收集猫狗信息，清晰正面照（好看一点），常驻地，毛色，瞳色，大小，性情。正准备申请网盘，申请好后请大家上传以免重复。
